"""
Author: Aimilios Leftheriotis
Affiliations: Microlab@NTUA, VLSILab@UPatras

This module defines the MyServer class, which inherits from the {Pair}Server class defined in the {pair}_server module, depending on the target AI-framework/platform pair.

Methods:
- __init__(self, logger): Initializes the MyServer instance, sets up the logger, and calls the method to set experiment configurations.

DO NOT edit this file directly.
"""

# Custom module
import arm_tf_server

class MyServer(arm_tf_server.ArmTfServer):
    def __init__(self, logger):
        super().__init__(logger)